# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 07:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_academyindexpage_contactusindexpage_enterprisecultureindexpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsindexpage',
            options={'verbose_name': '资讯中心二级页面'},
        ),
    ]
