# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20180109_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academyindexpage',
            options={'verbose_name': '金控学院二级页面'},
        ),
        migrations.AlterModelOptions(
            name='businessindexpage',
            options={'verbose_name': '集团业务二级页面'},
        ),
        migrations.AlterModelOptions(
            name='companyindexpage',
            options={'verbose_name': '走进金控二级页面'},
        ),
        migrations.AlterModelOptions(
            name='contactusindexpage',
            options={'verbose_name': '联系我们二级页面'},
        ),
        migrations.AlterModelOptions(
            name='enterprisecultureindexpage',
            options={'verbose_name': '企业文化二级页面'},
        ),
        migrations.AlterModelOptions(
            name='partybuildingindexpage',
            options={'verbose_name': '党建工作二级页面'},
        ),
    ]
