# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-13 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('news', '0009_newspage_representative_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': '专栏',
            },
            bases=('wagtailcore.page',),
        ),
    ]
