# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-25 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20180125_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisepage',
            name='enterprise_category',
            field=models.CharField(choices=[('全资企业', '全资企业'), ('控股企业', '控股企业'), ('参股企业', '参股企业')], default=1, max_length=10, verbose_name='公司类型'),
        ),
    ]
