# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20180125_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdomain',
            name='business_category',
            field=models.CharField(choices=[('主金融', '主金融'), ('类金融', '类金融'), ('平台类', '平台类')], default=1, max_length=10, verbose_name='业务领域'),
        ),
    ]
