# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_businessdomain_business_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdomain',
            name='business_name',
            field=models.CharField(max_length=60, verbose_name='业务名称'),
        ),
    ]
