# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-28 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('news', '0019_auto_20180128_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteLinkPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('link_category', models.CharField(choices=[('友情链接', '友情链接'), ('集团链接', '集团链接')], default=1, max_length=10, verbose_name='链接类型')),
                ('site_name', models.CharField(max_length=60, verbose_name='链接名称')),
                ('link_href', models.CharField(max_length=200, verbose_name='网址')),
            ],
            options={
                'verbose_name': '网站链接',
            },
            bases=('wagtailcore.page',),
        ),
    ]
