# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-29 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_websitelinkpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='enterprise_category',
            field=models.CharField(choices=[('thumbnail', '图片内容'), ('textonly', '文本内容'), ('singlepage', '单页内容')], default=1, max_length=10, verbose_name='内容类型'),
        ),
    ]
