# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-29 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_newspage_enterprise_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspage',
            old_name='enterprise_category',
            new_name='news_category',
        ),
    ]
