# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-11 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_auto_20180208_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formpage',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='to_address',
        ),
    ]
