# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-23 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_auto_20180211_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdomain',
            name='business_category',
            field=models.CharField(choices=[('主金融', '1主金融'), ('类金融', '2类金融'), ('平台类', '3平台类'), ('其他类', '4其他类')], default=1, max_length=10, verbose_name='业务领域'),
        ),
    ]
