# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-23 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0029_auto_20180223_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdomain',
            name='business_category',
            field=models.CharField(choices=[('1主金融', '主金融'), ('2类金融', '类金融'), ('3平台类', '平台类'), ('4其他类', '其他类')], default=1, max_length=10, verbose_name='业务领域'),
        ),
    ]
