# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-23 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0030_auto_20180223_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdomain',
            name='business_category',
            field=models.CharField(choices=[('1主金融', '1主金融'), ('2类金融', '2类金融'), ('3平台类', '3平台类'), ('4其他类', '4其他类')], default=1, max_length=10, verbose_name='业务领域'),
        ),
    ]
