# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-03 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0035_auto_20180503_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='news_category',
            field=models.CharField(choices=[('thumbnail', '图片内容'), ('textonly', '文本内容'), ('video', '视频内容'), ('singlepage', '单页内容'), ('partybuildtheory', '党建苑地')], default=1, max_length=30, verbose_name='内容类型'),
        ),
    ]
