# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-05 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('wagtailcore', '0040_page_draft_title'),
        ('news', '0038_industrialdevelopmentfundindexpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustrialDevelopmentFund',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('fund_name', models.CharField(max_length=60, verbose_name='产业发展投资基金名称')),
                ('fund_intro', wagtail.core.fields.RichTextField(blank=True, verbose_name='产业发展投资基金简介')),
                ('fund_intro_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='产业发展基金图片')),
            ],
            options={
                'verbose_name': '产业发展投资基金',
            },
            bases=('wagtailcore.page',),
        ),
    ]
