# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-09 02:00
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0041_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='table',
            field=wagtail.core.fields.StreamField((('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock())), blank=True),
        ),
    ]
