# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-23 08:33
from __future__ import unicode_literals

from django.db import migrations
import news.ueditor_richtext_field


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0043_remove_newspage_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='extro',
            field=news.ueditor_richtext_field.UEditorRichTextField(blank=True),
        ),
    ]
