# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-19 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0044_subadbanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subadbanner',
            options={'verbose_name': '宣传banner'},
        ),
        migrations.AlterField(
            model_name='subadbanner',
            name='banner_img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='宣传广告图片 1108*140'),
        ),
        migrations.AlterField(
            model_name='subadbanner',
            name='link_href',
            field=models.CharField(blank=True, max_length=500, verbose_name='链接地址'),
        ),
    ]
