# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-28 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0044_newspage_extro'),
        ('news', '0045_auto_20180519_0415'),
    ]

    operations = [
    ]
