# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-16 06:28
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0046_merge_20180528_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='stream_test',
            field=wagtail.core.fields.StreamField((('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())), blank=True),
        ),
    ]
