# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-19 12:34
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0047_newspage_stream_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspage',
            name='extro',
        ),
        migrations.AlterField(
            model_name='newspage',
            name='stream_test',
            field=wagtail.core.fields.StreamField((('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.core.blocks.StreamBlock((('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(classname='img-caption')))))), blank=True),
        ),
    ]
