# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-19 12:59
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0049_auto_20180619_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='stream_test',
            field=wagtail.core.fields.StreamField((('image', wagtail.core.blocks.StreamBlock(())),), blank=True),
        ),
    ]
