# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-19 16:14
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0052_auto_20180619_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='stream_test',
            field=wagtail.core.fields.StreamField((('image', wagtail.core.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock(classname='news-image', required=True, verbose_name='图片')), ('image_caption', wagtail.core.blocks.CharBlock(required=False, verbose_name='图片摘要'))))),)),
        ),
    ]
