# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-19 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0054_auto_20180619_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspage',
            old_name='stream_test',
            new_name='image_streamfield',
        ),
    ]
