# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-16 07:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Content',
            new_name='ContentPage',
        ),
    ]
