# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-16 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0006_auto_20171216_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='ContentPage',
        ),
    ]
