# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-25 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20171216_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': '首页'},
        ),
    ]
